### ISSUE TITLE
RF Power Unit energy storage

### ISSUE THREAD

**Issue by drzpk** [AlmuraDev/SGCraft#21]
Seems like there's a bug with Stargate power units. They are supposed to act like a buffer, completely replacing naquadah as energy source. However, with an RF Stargate Power Unit attached to stargate, OC interface (`sg.energyAvailable()`) shows, that gate stores only about 50000 energy, while the amount of energy required to travel to Nether from Overworld is, in my case, about 71000 (`sg.energyToDial()`). This bug renders power units completely useless in inter-dimensional travels.

BTW: this doesn't look good:
![untitled](https://user-images.githubusercontent.com/27144202/43989916-84b3f2f4-9d53-11e8-99b4-6479f91b2fa5.png)

**Comment by Dockter** [comment]
BAH.... This slipped through my testing.  I had fixed this in a code that I didn't commit a week ago and forgot to circle back.

I'll fix later today.

**Comment by Dockter** [comment]
Fixed in 1.15.2 for both forge and api 7 versions.

Available here:  https://ore.spongepowered.org/Dockter/SGCraft/versions

**Comment by drzpk** [comment]
I'm afraid this issue isn't fixed yet. Energy requirements to travel between dimensions are still too great: RF power unit can't store enough power to establish a connection. Maybe you could increase power unit's capacity to about 8 000 000 RF, so it can be used for inter-dimensional travel (on default configuration).

**Comment by Dockter** [comment]
I am still tweaking this section after yesterdays re-write of the zpm implementation.
